# 108 zonas de carga CENACE (fuente: PML.MDA_D)
# Formato: (zona, sistema)

ZONAS = [
    # BCA (4)
    ("ENSENADA",        "BCA"),
    ("MEXICALI",        "BCA"),
    ("SANLUIS",         "BCA"),
    ("TIJUANA",         "BCA"),
    # BCS (3)
    ("CONSTITUCION",    "BCS"),
    ("LA-PAZ",          "BCS"),
    ("LOS-CABOS",       "BCS"),
    # SIN (101)
    ("ACAPULCO",        "SIN"),
    ("AGUASCALIENTES",  "SIN"),
    ("APATZINGAN",      "SIN"),
    ("CABORCA",         "SIN"),
    ("CAMARGO",         "SIN"),
    ("CAMPECHE",        "SIN"),
    ("CANCUN",          "SIN"),
    ("CARMEN",          "SIN"),
    ("CASAS-GRANDES",   "SIN"),
    ("CELAYA",          "SIN"),
    ("CENTRO-ORIENTE",  "SIN"),
    ("CENTRO-SUR",      "SIN"),
    ("CHETUMAL",        "SIN"),
    ("CHIHUAHUA",       "SIN"),
    ("CHILPANCINGO",    "SIN"),
    ("CHONTALPA",       "SIN"),
    ("CIENEGA",         "SIN"),
    ("COATZACOALCOS",   "SIN"),
    ("COLIMA",          "SIN"),
    ("CORDOBA",         "SIN"),
    ("CUAUHTEMOC",      "SIN"),
    ("CUAUTLA",         "SIN"),
    ("CUERNAVACA",      "SIN"),
    ("CULIACAN",        "SIN"),
    ("DURANGO",         "SIN"),
    ("FRESNILLO",       "SIN"),
    ("GUADALAJARA",     "SIN"),
    ("GUASAVE",         "SIN"),
    ("GUAYMAS",         "SIN"),
    ("HERMOSILLO",      "SIN"),
    ("HUAJUAPAN",       "SIN"),
    ("HUASTECA",        "SIN"),
    ("HUATULCO",        "SIN"),
    ("HUEJUTLA",        "SIN"),
    ("IGUALA",          "SIN"),
    ("IRAPUATO",        "SIN"),
    ("IXMIQUILPAN",     "SIN"),
    ("IZUCAR",          "SIN"),
    ("JIQUILPAN",       "SIN"),
    ("JUAREZ",          "SIN"),
    ("LAGUNA",          "SIN"),
    ("LAZARO-CARDENAS", "SIN"),
    ("LEON",            "SIN"),
    ("LOS-ALTOS",       "SIN"),
    ("LOS-MOCHIS",      "SIN"),
    ("LOS-RIOS",        "SIN"),
    ("LOS-TUXTLAS",     "SIN"),
    ("MANZANILLO",      "SIN"),
    ("MATAMOROS",       "SIN"),
    ("MATEHUALA",       "SIN"),
    ("MAZATLAN",        "SIN"),
    ("MERIDA",          "SIN"),
    ("MINAS",           "SIN"),
    ("MONCLOVA",        "SIN"),
    ("MONTEMORELOS",    "SIN"),
    ("MONTERREY",       "SIN"),
    ("MORELIA",         "SIN"),
    ("MORELOS",         "SIN"),
    ("MOTUL-TIZIMIN",   "SIN"),
    ("NAVOJOA",         "SIN"),
    ("NOGALES",         "SIN"),
    ("NUEVO-LAREDO",    "SIN"),
    ("OAXACA",          "SIN"),
    ("OBREGON",         "SIN"),
    ("ORIZABA",         "SIN"),
    ("PIEDRAS-NEGRAS",  "SIN"),
    ("POZA-RICA",       "SIN"),
    ("PUEBLA",          "SIN"),
    ("QUERETARO",       "SIN"),
    ("REYNOSA",         "SIN"),
    ("RIVIERA-MAYA",    "SIN"),
    ("SABINAS",         "SIN"),
    ("SALTILLO",        "SIN"),
    ("SALVATIERRA",     "SIN"),
    ("SAN-CRISTOBAL",   "SIN"),
    ("SAN-JUAN-DEL-RIO","SIN"),
    ("SAN-LUIS-POTOSI", "SIN"),
    ("SAN-MARTIN",      "SIN"),
    ("TAMPICO",         "SIN"),
    ("TAPACHULA",       "SIN"),
    ("TECAMACHALCO",    "SIN"),
    ("TEHUACAN",        "SIN"),
    ("TEHUANTEPEC",     "SIN"),
    ("TEPIC-VALLARTA",  "SIN"),
    ("TEZIUTLAN",       "SIN"),
    ("TICUL",           "SIN"),
    ("TLAXCALA",        "SIN"),
    ("TUXTLA",          "SIN"),
    ("URUAPAN",         "SIN"),
    ("VDM-CENTRO",      "SIN"),
    ("VDM-NORTE",       "SIN"),
    ("VDM-SUR",         "SIN"),
    ("VERACRUZ",        "SIN"),
    ("VICTORIA",        "SIN"),
    ("VILLAHERMOSA",    "SIN"),
    ("XALAPA",          "SIN"),
    ("ZACAPU",          "SIN"),
    ("ZACATECAS",       "SIN"),
    ("ZAMORA",          "SIN"),
    ("ZAPOTLAN",        "SIN"),
    ("ZIHUATANEJO",     "SIN"),
]

# Agrupadas por sistema para iterar facilmente
def zonas_por_sistema(sistema):
    return [z for z, s in ZONAS if s == sistema]
